export enum ShaderAttribute {
  Position = 'a_position',
  Normal = 'a_normal',
  TexCoord = 'a_texcoord',
  ViewProjectionMatrix = 'u_viewProjectionMatrix',
  WorldMatrix = 'u_worldMatrix',
  DiffuseColor = 'u_diffuseColor',
  SpecularColor = 'u_specularColor',
  DirectionLight = 'u_lightPos',
  Brightness = 'u_brightness',
  DiffuseTexture = 'u_diffuseTexture',
  UseDiffuseTexture = 'u_useDiffuseTexture',
  SpecularTexture = 'u_specularTexture',
  UseSpecularTexture = 'u_useSpecularTexture',
  ViewPosition = 'u_viewPos',
}
